# Generated by Django 4.1.4 on 2023-01-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dwitter", "0002_dweet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dweet",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
