# Generated by Django 4.1.4 on 2023-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dwitter", "0003_rename_create_at_dweet_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="imgg",
            field=models.FilePathField(default=0, path="/img"),
            preserve_default=False,
        ),
    ]
