# Generated by Django 4.1.4 on 2023-01-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dwitter", "0004_profile_imgg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="imgg",
            new_name="image",
        ),
    ]
